//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSBourse.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bourseContainer : DbContext
    {
        public bourseContainer()
            : base("name=bourseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<SoldProduct> SoldProductSet { get; set; }
        public virtual DbSet<Transaction> TransactionSet { get; set; }
        public virtual DbSet<BuyTransaction> BuyTransactionSet { get; set; }
        public virtual DbSet<EmittedCoupon> EmittedCouponSet { get; set; }
        public virtual DbSet<EnteredCoupon> EnteredCouponSet1 { get; set; }
        public virtual DbSet<EnteredDirectExchange> EnteredDirectExchangeSet1 { get; set; }
        public virtual DbSet<EnteredDiscount> EnteredDiscountSet { get; set; }
        public virtual DbSet<CashInput> CashInputSet { get; set; }
        public virtual DbSet<CashOutput> CashOutputSet { get; set; }
        public virtual DbSet<Parameters> ParametersSet { get; set; }
    }
}
