//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSBourse.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoldProduct
    {
        public int Id { get; set; }
        public System.DateTime datetime { get; set; }
        public decimal price { get; set; }
        public int TransactionId { get; set; }
        public bool inStock { get; set; }
        public string code { get; set; }
        public string title { get; set; }
        public string author { get; set; }
        public string type { get; set; }
        public string editor { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
